---
title: "CodeBook"
author: "Anush"
date: "27/05/2020"
output:
  pdf_document: default
  html_document: default
  word_document: default
---


# Getting And Cleaning Data

# Modifications 

## the original data was modified by

1. Merged the training and the test sets to create one data set.
2. Extracted only the measurements on the mean and standard deviation for each measurement.

3. Used descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, created a second, independent tidy data set with the average of each variable for each activity and each subject.

# Descriptions

## Identifiers

**The first two columns - Subject and Activity - are Identifiers.**

**Subject:** the ID of the Subject

**Activity:** the Name of the Activity performed by the subject when measurements were taken

## Measurements

*As mentioned above,the variables remaining are just the calculatd means and standard deviations of these sets of data: (Even if I do not give a detailed description of what each data value means, you can see what it means by comparing it with the original data column.)*

- tBodyAccMeanX

-tBodyAccMeanY

-tBodyAccMeanZ

-tBodyAccStdX

-tBodyAccStdY

-tBodyAccStdZ

-tGravityAccMeanX

-tGravityAccMeanY

-tGravityAccMeanZ

-tGravityAccStdX 

-tGravityAccStdY

-tGravityAccStdZ

-tBodyAccJerkMeanX

-tBodyAccJerkMeanY

-tBodyAccJerkMeanZ

-tBodyAccJerkStdX

-tBodyAccJerkStdY

-tBodyAccJerkStdZ

-tBodyGyroMeanX

-tBodyGyroMeanY

-tBodyGyroMeanZ

-tBodyGyroStdX

-tBodyGyroStdY

-tBodyGyroStdZ

-tBodyGyroJerkMeanX

-tBodyGyroJerkMeanY

-tBodyGyroJerkMeanZ

-tBodyGyroJerkStdX

-tBodyGyroJerkStdY

-tBodyGyroJerkStdZ

-tBodyAccMagMean

-tBodyAccMagStd

-tGravityAccMagMean

-tGravityAccMagStd

-tBodyAccJerkMagMean

-tBodyAccJerkMagStd

-tBodyGyroMagMean

-tBodyGyroMagStd

-tBodyGyroJerkMagMean

-tBodyGyroJerkMagStd

-fBodyAccMeanX

-fBodyAccMeanY

-fBodyAccMeanZ

-fBodyAccStdX

-fBodyAccStdY

-fBodyAccStdZ

-fBodyAccMeanFreqX

-fBodyAccMeanFreqY

-fBodyAccMeanFreqZ

-fBodyAccJerkMeanX

-fBodyAccJerkMeanY

-fBodyAccJerkMeanZ

-fBodyAccJerkStdX

-fBodyAccJerkStdY

-fBodyAccJerkStdZ

-fBodyAccJerkMeanFreqX

-fBodyAccJerkMeanFreqY

-fBodyAccJerkMeanFreqZ

-fBodyGyroMeanX

-fBodyGyroMeanY

-fBodyGyroMeanZ

-fBodyGyroStdX

-fBodyGyroStdY

-fBodyGyroStdZ

-fBodyGyroMeanFreqX

-fBodyGyroMeanFreqY

-fBodyGyroMeanFreqZ

-fBodyAccMagMean

-fBodyAccMagStd

-fBodyAccMagMeanFreq

-fBodyBodyAccJerkMagMean

-fBodyBodyAccJerkMagStd

-fBodyBodyAccJerkMagMeanFreq

-fBodyBodyGyroMagMean

-fBodyBodyGyroMagStd

-fBodyBodyGyroMagMeanFreq

-fBodyBodyGyroJerkMagMean

-fBodyBodyGyroJerkMagStd

-fBodyBodyGyroJerkMagMeanFreq